### ISSUE TITLE
End point update

### ISSUE THREAD

**Issue by Jishnukj** [joelsunny98/.net-fundametals#74]
![image](https://github.com/joelsunny98/.net-fundametals/assets/38211684/bedeef60-685d-4e31-8bae-aa0dc0d5d2f5)

suggestion: customers/premium

in the same controller try to start the endpoint with the same name

please look into other controllers also 

![image](https://github.com/joelsunny98/.net-fundametals/assets/38211684/f832418d-4313-4ee2-b0e2-a3f51385ddd6)
![image](https://github.com/joelsunny98/.net-fundametals/assets/38211684/45bad774-58ec-473d-8bc8-04714db4dd27)

**Comment by austinsp135** [comment]
Done

**Comment by Jishnukj** [comment]
HttpPut("product") not updated

**Comment by josmyabraham99** [comment]
![image](https://github.com/joelsunny98/.net-fundametals/assets/114714197/40117cd6-7257-4c58-9391-800bc5299041)

**Comment by Jishnukj** [comment]
But Id seems like not used anywhere.
Also update product to products.

**Comment by austinsp135** [comment]
![image](https://github.com/joelsunny98/.net-fundametals/assets/60867807/489c1e6d-3f6d-4b01-bc10-8bec7ca59004)

**Comment by joelsunny98** [comment]
I've also updated the sms endpoint. Please take a look at the changes and let us know if there is anything else
