### ISSUE TITLE
Magic Numbers

### ISSUE THREAD

**Issue by Jishnukj** [joelsunny98/.net-fundametals#78]
Magic Numbers in TotalValue Extension.
RetailStore/Extensions/CalculateAmount.cs

**Comment by joelsunny98** [comment]
I've Added the constants for the magic numbers and the string values in other helpers.

**Comment by Jishnukj** [comment]
RetailStore/Helpers/PremiumCustomersHelper.cs

In this file can we use name like PremiumCustomerMinValue instead of FiveThousand based on business logic? 

So that if we need to update the amount, only need to update the value no need to update constant name.

Do same in RetailStore/Helpers/AmountHelper.cs

Instead of Constant.Thousand, Constant.TwoThousand 
use const like 
TenPercentDiscountMinValue, TenPercentDiscountMaxValue

**Comment by joelsunny98** [comment]
I've updated the helpers with these changes. Please take a look.
